name: "Setup QEMU"
description: "Setup QEMU for arm64 architecture"
inputs:
  arch:
    description: "Architecture to set up QEMU for"
    required: true
    default: "x64"

runs:
  using: "composite"
  steps:
    - name: Setup QEMU
      if: ${{ inputs.arch == 'arm64' }}
      uses: docker/setup-qemu-action@1f40c72289eff860ee54a304f1438e3cff362e0a # v4.3.0
      with:
        platforms: linux/arm64
