name: Code Quality

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:native:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tidy
      
      - name: Install Node dependencies
        run: npm ci
      
      - name: Build project
        run: npm run build
      
      - name: Run clang-tidy
        run: npm run lint:native
        
  memory-tests-basic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y valgrind
      
      - name: Install Node dependencies
        run: npm ci
      
      - name: Build project
        run: npm run build
      
      - name: Run JavaScript memory tests
        run: npm run memory:test
      
      - name: Run valgrind tests
        run: bash scripts/valgrind.sh