name: Memory Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Comprehensive memory tests - all platforms and Node versions
  memory-tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [20, 22, 23, 24]
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y valgrind build-essential clang
      
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build native and javascript bundle
        run: npm run build
      
      - name: Run comprehensive memory tests
        run: npm run check:memory
      
      - name: Upload memory test artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: memory-test-results-${{ matrix.os }}-node${{ matrix.node-version }}
          path: |
            asan-test.log
            valgrind.log
            asan-output.log
          if-no-files-found: ignore